'use client';
import type { Metadata } from 'next';
import { Toaster } from '@/components/ui/sonner';
import { Analytics } from "@vercel/analytics/react"
import { Inter } from 'next/font/google';
import './globals.css';
import { ApolloProvider } from '@apollo/client';
import client from '@/lib/graphql/client';
import { ClerkProvider } from '@clerk/nextjs';
import Header from '@/components/custom/Header';
import { Footer } from '@/components/custom/Fotter';
import { SpeedInsights } from "@vercel/speed-insights/next"
const inter = Inter({ subsets: ['latin'] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <ApolloProvider client={client}>
            <Toaster richColors expand={true} position="top-right" />
            <Header />

            {children}
            <Footer />
            <Analytics />
            <SpeedInsights />

          </ApolloProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
